spring:
  datasource:
    driverClassName: org.postgresql.Driver
    username: pramaswa
    password: ""
    url: jdbc:postgresql://localhost:5432/sboot_demo
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
logging:
  level:
    org:
      hibernate:
        SQL: debug


server:
  port: 8180
  contextPath: /SpringIODemo

hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  show_sql: true
  format_sql: true
  hbm2ddl:
    auto: none

app:
  env: blue1

